# Generated by Django 5.2.8 on 2025-11-28 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login_flow', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='name',
            new_name='username',
        ),
    ]
